using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnet_test.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if Players table already exists before creating it
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Players') THEN
                        CREATE TABLE ""Players"" (
                            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            ""PlayerId"" character varying(50) NOT NULL,
                            ""DaysSinceJoined"" integer NOT NULL,
                            ""MostBetSport"" character varying(100) NOT NULL,
                            ""FavouriteTeam"" character varying(100) NOT NULL,
                            ""MostBetType"" character varying(100) NOT NULL,
                            ""AverageStake"" numeric(10,2) NOT NULL,
                            ""LastLoginDaysAgo"" integer NOT NULL,
                            ""RiskLevel"" character varying(20) NOT NULL,
                            ""IsSelfExcluded"" boolean NOT NULL,
                            ""CoolingOffUntilUtc"" timestamp with time zone,
                            ""JurisdictionCode"" character varying(20) NOT NULL,
                            ""IsRecommendationRestricted"" boolean NOT NULL,
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            ""UpdatedAt"" timestamp with time zone,
                            PRIMARY KEY (""Id"")
                        );
                        CREATE UNIQUE INDEX ""IX_Players_PlayerId"" ON ""Players"" (""PlayerId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Players");
        }
    }
}
